version: "3"

services:
  # Mongo DB 4.2.5
  # https://hub.docker.com/layers/mongo/library/mongo/4.2.5-bionic/images/sha256-e02955d5aad655bff95edfd8860add767a75a760d7952966cbd3a01202684e95?context=explore
  mongo-database:
    image: mongo:4.2.5-bionic
    container_name: database
    # Database does not expose any port
    # https://docs.docker.com/compose/compose-file/#expose
    expose:
      - "27017"
    # https://hub.docker.com/_/mongo?tab=description
    environment:
      MONGO_INITDB_ROOT_USERNAME: pouet
      MONGO_INITDB_ROOT_PASSWORD: pouet
      MONGO_INITDB_DATABASE: alun
    # volumes:
    #   db-data:
    networks:
      alun:
        aliases:
          - mongo-database

  api:
    container_name: api
    build:
      context: ./../alun-api
      dockerfile: api-monolith.Dockerfile
    ports:
      - "8000:8000"
    # Specify local .env file to avoid committing secret
    # https://docs.docker.com/compose/compose-file/#env_file
    env_file:
      - ./../alun-api/.env.docker
    # Those variables are compose-dependent so they must be defined here
    environment:
      ALUN_SERVER_MONOLITHIC_PORT: 8000
      ALUN_CLIENT_DOMAIN: http://localhost:8080
      ALUN_USER_DATABASE_URL: mongodb://pouet:pouet@mongo-database:27017/alun
      ALUN_MEMO_DATABASE_URL: mongodb://pouet:pouet@mongo-database:27017/alun
    networks:
      alun:
        aliases:
          - api
    depends_on:
      - mongo-database

  frontend-app:
    container_name: app
    build:
      context: ./../alun-app
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      alun:
        aliases:
          - app
    depends_on:
      - api

volumes:
  db-data:

networks:
  alun:
    ipam:
      driver: default
      config:
        - subnet: "172.42.39.0/24"